name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
      - trunk

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  hisel_tests:
    name: "hisel tests"
    runs-on:
      - self-hosted
      - production
      - xlarge
    container: docker.tw.ee/actions_python3

    steps:
      # GHA leaves mess behind. We need to clear those or our we end up having unexpected behaviours.
      # REMOVE ME when A&T uses ephemeral runners
      - name: Clear dirty runner
        # Clear everything, both home and working directory
        run: |
          rm -rfv ~/* ./* || true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - name: Installing hisel dependencies
        run: |
          virtualenv hisel-env
          source hisel-env/bin/activate
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install poetry
          poetry lock
          poetry install --with test

      - name: Run hisel tests
        run: |
          source hisel-env/bin/activate
          poetry run pytest tests/kernel_test.py --disable-warnings
          poetry run pytest tests/torchkernel_test.py --disable-warnings
          poetry run pytest tests/lar_test.py --disable-warnings
          poetry run pytest tests/select_test.py --disable-warnings

  run_trufflehog:
    name: "Run trufflehog to catch credential leaks"
    runs-on:
      - self-hosted
      - production
      - medium
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug
